/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuickGigsEnrollRouteImport } from './routes/quick-gigs/enroll'
import { Route as PortfolioUsernameRouteImport } from './routes/portfolio/$username'
import { Route as AppSwitchRouteImport } from './routes/_app/switch'
import { Route as JobSearchSeekerEnrollRouteImport } from './routes/job-search/seeker/enroll'
import { Route as JobSearchSeekerAssessmentRouteImport } from './routes/job-search/seeker/assessment'
import { Route as JobSearchCompanyEnrollRouteImport } from './routes/job-search/company/enroll'
import { Route as AppQuickGigsEarnerProfileRouteImport } from './routes/_app/quick-gigs/earner/profile'
import { Route as AppQuickGigsEarnerFeedRouteImport } from './routes/_app/quick-gigs/earner/feed'
import { Route as AppQuickGigsBusinessPostBountyRouteImport } from './routes/_app/quick-gigs/business/post-bounty'
import { Route as AppQuickGigsBusinessDashboardRouteImport } from './routes/_app/quick-gigs/business/dashboard'
import { Route as AppQuickGigsBountyIdRouteImport } from './routes/_app/quick-gigs/bounty/$id'
import { Route as AppJobSearchSeekerProfileRouteImport } from './routes/_app/job-search/seeker/profile'
import { Route as AppJobSearchSeekerFeedRouteImport } from './routes/_app/job-search/seeker/feed'
import { Route as AppJobSearchCompanyPlansRouteImport } from './routes/_app/job-search/company/plans'
import { Route as AppJobSearchCompanyDashboardRouteImport } from './routes/_app/job-search/company/dashboard'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickGigsEnrollRoute = QuickGigsEnrollRouteImport.update({
  id: '/quick-gigs/enroll',
  path: '/quick-gigs/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioUsernameRoute = PortfolioUsernameRouteImport.update({
  id: '/portfolio/$username',
  path: '/portfolio/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSwitchRoute = AppSwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => AppRoute,
} as any)
const JobSearchSeekerEnrollRoute = JobSearchSeekerEnrollRouteImport.update({
  id: '/job-search/seeker/enroll',
  path: '/job-search/seeker/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSearchSeekerAssessmentRoute =
  JobSearchSeekerAssessmentRouteImport.update({
    id: '/job-search/seeker/assessment',
    path: '/job-search/seeker/assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobSearchCompanyEnrollRoute = JobSearchCompanyEnrollRouteImport.update({
  id: '/job-search/company/enroll',
  path: '/job-search/company/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQuickGigsEarnerProfileRoute =
  AppQuickGigsEarnerProfileRouteImport.update({
    id: '/quick-gigs/earner/profile',
    path: '/quick-gigs/earner/profile',
    getParentRoute: () => AppRoute,
  } as any)
const AppQuickGigsEarnerFeedRoute = AppQuickGigsEarnerFeedRouteImport.update({
  id: '/quick-gigs/earner/feed',
  path: '/quick-gigs/earner/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppQuickGigsBusinessPostBountyRoute =
  AppQuickGigsBusinessPostBountyRouteImport.update({
    id: '/quick-gigs/business/post-bounty',
    path: '/quick-gigs/business/post-bounty',
    getParentRoute: () => AppRoute,
  } as any)
const AppQuickGigsBusinessDashboardRoute =
  AppQuickGigsBusinessDashboardRouteImport.update({
    id: '/quick-gigs/business/dashboard',
    path: '/quick-gigs/business/dashboard',
    getParentRoute: () => AppRoute,
  } as any)
const AppQuickGigsBountyIdRoute = AppQuickGigsBountyIdRouteImport.update({
  id: '/quick-gigs/bounty/$id',
  path: '/quick-gigs/bounty/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppJobSearchSeekerProfileRoute =
  AppJobSearchSeekerProfileRouteImport.update({
    id: '/job-search/seeker/profile',
    path: '/job-search/seeker/profile',
    getParentRoute: () => AppRoute,
  } as any)
const AppJobSearchSeekerFeedRoute = AppJobSearchSeekerFeedRouteImport.update({
  id: '/job-search/seeker/feed',
  path: '/job-search/seeker/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppJobSearchCompanyPlansRoute =
  AppJobSearchCompanyPlansRouteImport.update({
    id: '/job-search/company/plans',
    path: '/job-search/company/plans',
    getParentRoute: () => AppRoute,
  } as any)
const AppJobSearchCompanyDashboardRoute =
  AppJobSearchCompanyDashboardRouteImport.update({
    id: '/job-search/company/dashboard',
    path: '/job-search/company/dashboard',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/switch': typeof AppSwitchRoute
  '/portfolio/$username': typeof PortfolioUsernameRoute
  '/quick-gigs/enroll': typeof QuickGigsEnrollRoute
  '/job-search/company/enroll': typeof JobSearchCompanyEnrollRoute
  '/job-search/seeker/assessment': typeof JobSearchSeekerAssessmentRoute
  '/job-search/seeker/enroll': typeof JobSearchSeekerEnrollRoute
  '/job-search/company/dashboard': typeof AppJobSearchCompanyDashboardRoute
  '/job-search/company/plans': typeof AppJobSearchCompanyPlansRoute
  '/job-search/seeker/feed': typeof AppJobSearchSeekerFeedRoute
  '/job-search/seeker/profile': typeof AppJobSearchSeekerProfileRoute
  '/quick-gigs/bounty/$id': typeof AppQuickGigsBountyIdRoute
  '/quick-gigs/business/dashboard': typeof AppQuickGigsBusinessDashboardRoute
  '/quick-gigs/business/post-bounty': typeof AppQuickGigsBusinessPostBountyRoute
  '/quick-gigs/earner/feed': typeof AppQuickGigsEarnerFeedRoute
  '/quick-gigs/earner/profile': typeof AppQuickGigsEarnerProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/switch': typeof AppSwitchRoute
  '/portfolio/$username': typeof PortfolioUsernameRoute
  '/quick-gigs/enroll': typeof QuickGigsEnrollRoute
  '/job-search/company/enroll': typeof JobSearchCompanyEnrollRoute
  '/job-search/seeker/assessment': typeof JobSearchSeekerAssessmentRoute
  '/job-search/seeker/enroll': typeof JobSearchSeekerEnrollRoute
  '/job-search/company/dashboard': typeof AppJobSearchCompanyDashboardRoute
  '/job-search/company/plans': typeof AppJobSearchCompanyPlansRoute
  '/job-search/seeker/feed': typeof AppJobSearchSeekerFeedRoute
  '/job-search/seeker/profile': typeof AppJobSearchSeekerProfileRoute
  '/quick-gigs/bounty/$id': typeof AppQuickGigsBountyIdRoute
  '/quick-gigs/business/dashboard': typeof AppQuickGigsBusinessDashboardRoute
  '/quick-gigs/business/post-bounty': typeof AppQuickGigsBusinessPostBountyRoute
  '/quick-gigs/earner/feed': typeof AppQuickGigsEarnerFeedRoute
  '/quick-gigs/earner/profile': typeof AppQuickGigsEarnerProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/switch': typeof AppSwitchRoute
  '/portfolio/$username': typeof PortfolioUsernameRoute
  '/quick-gigs/enroll': typeof QuickGigsEnrollRoute
  '/job-search/company/enroll': typeof JobSearchCompanyEnrollRoute
  '/job-search/seeker/assessment': typeof JobSearchSeekerAssessmentRoute
  '/job-search/seeker/enroll': typeof JobSearchSeekerEnrollRoute
  '/_app/job-search/company/dashboard': typeof AppJobSearchCompanyDashboardRoute
  '/_app/job-search/company/plans': typeof AppJobSearchCompanyPlansRoute
  '/_app/job-search/seeker/feed': typeof AppJobSearchSeekerFeedRoute
  '/_app/job-search/seeker/profile': typeof AppJobSearchSeekerProfileRoute
  '/_app/quick-gigs/bounty/$id': typeof AppQuickGigsBountyIdRoute
  '/_app/quick-gigs/business/dashboard': typeof AppQuickGigsBusinessDashboardRoute
  '/_app/quick-gigs/business/post-bounty': typeof AppQuickGigsBusinessPostBountyRoute
  '/_app/quick-gigs/earner/feed': typeof AppQuickGigsEarnerFeedRoute
  '/_app/quick-gigs/earner/profile': typeof AppQuickGigsEarnerProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/switch'
    | '/portfolio/$username'
    | '/quick-gigs/enroll'
    | '/job-search/company/enroll'
    | '/job-search/seeker/assessment'
    | '/job-search/seeker/enroll'
    | '/job-search/company/dashboard'
    | '/job-search/company/plans'
    | '/job-search/seeker/feed'
    | '/job-search/seeker/profile'
    | '/quick-gigs/bounty/$id'
    | '/quick-gigs/business/dashboard'
    | '/quick-gigs/business/post-bounty'
    | '/quick-gigs/earner/feed'
    | '/quick-gigs/earner/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/switch'
    | '/portfolio/$username'
    | '/quick-gigs/enroll'
    | '/job-search/company/enroll'
    | '/job-search/seeker/assessment'
    | '/job-search/seeker/enroll'
    | '/job-search/company/dashboard'
    | '/job-search/company/plans'
    | '/job-search/seeker/feed'
    | '/job-search/seeker/profile'
    | '/quick-gigs/bounty/$id'
    | '/quick-gigs/business/dashboard'
    | '/quick-gigs/business/post-bounty'
    | '/quick-gigs/earner/feed'
    | '/quick-gigs/earner/profile'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/switch'
    | '/portfolio/$username'
    | '/quick-gigs/enroll'
    | '/job-search/company/enroll'
    | '/job-search/seeker/assessment'
    | '/job-search/seeker/enroll'
    | '/_app/job-search/company/dashboard'
    | '/_app/job-search/company/plans'
    | '/_app/job-search/seeker/feed'
    | '/_app/job-search/seeker/profile'
    | '/_app/quick-gigs/bounty/$id'
    | '/_app/quick-gigs/business/dashboard'
    | '/_app/quick-gigs/business/post-bounty'
    | '/_app/quick-gigs/earner/feed'
    | '/_app/quick-gigs/earner/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PortfolioUsernameRoute: typeof PortfolioUsernameRoute
  QuickGigsEnrollRoute: typeof QuickGigsEnrollRoute
  JobSearchCompanyEnrollRoute: typeof JobSearchCompanyEnrollRoute
  JobSearchSeekerAssessmentRoute: typeof JobSearchSeekerAssessmentRoute
  JobSearchSeekerEnrollRoute: typeof JobSearchSeekerEnrollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-gigs/enroll': {
      id: '/quick-gigs/enroll'
      path: '/quick-gigs/enroll'
      fullPath: '/quick-gigs/enroll'
      preLoaderRoute: typeof QuickGigsEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$username': {
      id: '/portfolio/$username'
      path: '/portfolio/$username'
      fullPath: '/portfolio/$username'
      preLoaderRoute: typeof PortfolioUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/switch': {
      id: '/_app/switch'
      path: '/switch'
      fullPath: '/switch'
      preLoaderRoute: typeof AppSwitchRouteImport
      parentRoute: typeof AppRoute
    }
    '/job-search/seeker/enroll': {
      id: '/job-search/seeker/enroll'
      path: '/job-search/seeker/enroll'
      fullPath: '/job-search/seeker/enroll'
      preLoaderRoute: typeof JobSearchSeekerEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-search/seeker/assessment': {
      id: '/job-search/seeker/assessment'
      path: '/job-search/seeker/assessment'
      fullPath: '/job-search/seeker/assessment'
      preLoaderRoute: typeof JobSearchSeekerAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-search/company/enroll': {
      id: '/job-search/company/enroll'
      path: '/job-search/company/enroll'
      fullPath: '/job-search/company/enroll'
      preLoaderRoute: typeof JobSearchCompanyEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/quick-gigs/earner/profile': {
      id: '/_app/quick-gigs/earner/profile'
      path: '/quick-gigs/earner/profile'
      fullPath: '/quick-gigs/earner/profile'
      preLoaderRoute: typeof AppQuickGigsEarnerProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quick-gigs/earner/feed': {
      id: '/_app/quick-gigs/earner/feed'
      path: '/quick-gigs/earner/feed'
      fullPath: '/quick-gigs/earner/feed'
      preLoaderRoute: typeof AppQuickGigsEarnerFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quick-gigs/business/post-bounty': {
      id: '/_app/quick-gigs/business/post-bounty'
      path: '/quick-gigs/business/post-bounty'
      fullPath: '/quick-gigs/business/post-bounty'
      preLoaderRoute: typeof AppQuickGigsBusinessPostBountyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quick-gigs/business/dashboard': {
      id: '/_app/quick-gigs/business/dashboard'
      path: '/quick-gigs/business/dashboard'
      fullPath: '/quick-gigs/business/dashboard'
      preLoaderRoute: typeof AppQuickGigsBusinessDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quick-gigs/bounty/$id': {
      id: '/_app/quick-gigs/bounty/$id'
      path: '/quick-gigs/bounty/$id'
      fullPath: '/quick-gigs/bounty/$id'
      preLoaderRoute: typeof AppQuickGigsBountyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/job-search/seeker/profile': {
      id: '/_app/job-search/seeker/profile'
      path: '/job-search/seeker/profile'
      fullPath: '/job-search/seeker/profile'
      preLoaderRoute: typeof AppJobSearchSeekerProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/job-search/seeker/feed': {
      id: '/_app/job-search/seeker/feed'
      path: '/job-search/seeker/feed'
      fullPath: '/job-search/seeker/feed'
      preLoaderRoute: typeof AppJobSearchSeekerFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/job-search/company/plans': {
      id: '/_app/job-search/company/plans'
      path: '/job-search/company/plans'
      fullPath: '/job-search/company/plans'
      preLoaderRoute: typeof AppJobSearchCompanyPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/job-search/company/dashboard': {
      id: '/_app/job-search/company/dashboard'
      path: '/job-search/company/dashboard'
      fullPath: '/job-search/company/dashboard'
      preLoaderRoute: typeof AppJobSearchCompanyDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSwitchRoute: typeof AppSwitchRoute
  AppJobSearchCompanyDashboardRoute: typeof AppJobSearchCompanyDashboardRoute
  AppJobSearchCompanyPlansRoute: typeof AppJobSearchCompanyPlansRoute
  AppJobSearchSeekerFeedRoute: typeof AppJobSearchSeekerFeedRoute
  AppJobSearchSeekerProfileRoute: typeof AppJobSearchSeekerProfileRoute
  AppQuickGigsBountyIdRoute: typeof AppQuickGigsBountyIdRoute
  AppQuickGigsBusinessDashboardRoute: typeof AppQuickGigsBusinessDashboardRoute
  AppQuickGigsBusinessPostBountyRoute: typeof AppQuickGigsBusinessPostBountyRoute
  AppQuickGigsEarnerFeedRoute: typeof AppQuickGigsEarnerFeedRoute
  AppQuickGigsEarnerProfileRoute: typeof AppQuickGigsEarnerProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSwitchRoute: AppSwitchRoute,
  AppJobSearchCompanyDashboardRoute: AppJobSearchCompanyDashboardRoute,
  AppJobSearchCompanyPlansRoute: AppJobSearchCompanyPlansRoute,
  AppJobSearchSeekerFeedRoute: AppJobSearchSeekerFeedRoute,
  AppJobSearchSeekerProfileRoute: AppJobSearchSeekerProfileRoute,
  AppQuickGigsBountyIdRoute: AppQuickGigsBountyIdRoute,
  AppQuickGigsBusinessDashboardRoute: AppQuickGigsBusinessDashboardRoute,
  AppQuickGigsBusinessPostBountyRoute: AppQuickGigsBusinessPostBountyRoute,
  AppQuickGigsEarnerFeedRoute: AppQuickGigsEarnerFeedRoute,
  AppQuickGigsEarnerProfileRoute: AppQuickGigsEarnerProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PortfolioUsernameRoute: PortfolioUsernameRoute,
  QuickGigsEnrollRoute: QuickGigsEnrollRoute,
  JobSearchCompanyEnrollRoute: JobSearchCompanyEnrollRoute,
  JobSearchSeekerAssessmentRoute: JobSearchSeekerAssessmentRoute,
  JobSearchSeekerEnrollRoute: JobSearchSeekerEnrollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
